### PR TITLE
[feat] Add additional suites

### LINKED ISSUE #4: Missing Suite - Suite__DHKEM_P256_HKDF_SHA256__HKDF_SHA256__AES_256_GCM ?
Is there any technical reason why this suite isn't defined?

```python
class Suite__DHKEM_P256_HKDF_SHA256__HKDF_SHA256__AES_256_GCM(_Suite):
    """
    This is DHKEM(P-256, HKDF-SHA256), HKDF-SHA256, AES-256-GCM
    """

    KEM = DHKEM_P256_HKDF_SHA256
    KDF = HKDF_SHA256
    AEAD = _AES_256_GCM
```

### PR DESCRIPTION
**Pull request by jplock**
Add new suites:
- `DHKEM_P256_HKDF_SHA256__HKDF_SHA256__AES_256_GCM`
- `DHKEM_P384_HKDF_SHA384__HKDF_SHA384__AES_256_GCM`

Fixes #4

### CODE REVIEW

**Comment by jplock** [comment]
@ctz would you be open to adding these additional suites?

**Comment by jplock** [comment]
Hi @ctz, any chance this could be merged and released? Thank you for the time and consideration.

**Review by ctz — APPROVED** [review]
Thanks & sorry for the delay.

**Comment by jplock** [comment]
thank you!

**Pull request merged**
